### ISSUE TITLE
Supporting Python3

### ISSUE THREAD

**Issue by kristiank** [YelpArchive/sqlite3dbm#11]
Is there any plans for supporting Python3?

I might be able to help with some tasks in that case.

This question is also related to Issue #10 about installing with Pip for Python3.

**Comment by coyotemarin** [comment]
Sure, sounds do-able. Might get to it after the v0.5.0 mrjob release.

**Comment by kristiank** [comment]
Do you have any time scheduled for that release?

**Comment by coyotemarin** [comment]
Oh! Have you tried https://pypi.python.org/pypi/sqlite_dbm/? It looks like it supports Python 3.

**Comment by kristiank** [comment]
Somehow my search results haven't shown it. I will have a look. Thank you!

**Comment by coyotemarin** [comment]
Yeah, Google isn't great for that somehow. I searched for "dbm" on PyPI to find it.

**Comment by coyotemarin** [comment]
Planning to eventually bring `sqlite3dbm` up-to-date and look into merging it with `sqlite_dbm`. Not sure of the timeline though.

**Comment by mvrozanti** [comment]
Quickfix for Python3:

I had this error appearing when I try to install this package using setup.py:

`Traceback (most recent call last):
  File "setup.py", line 1, in <module>
    from sqlite3dbm import __version__
  File "/home/nexor/sqlite3dbm/sqlite3dbm/__init__.py", line 23, in <module>
    import sqlite3dbm.dbm as dbm
  File "/home/nexor/sqlite3dbm/sqlite3dbm/dbm.py", line 197
    def __init__(self, path, flag='r', mode=0666):
                                               ^
SyntaxError: invalid token
`

I noticed `mode=0666` which I thought should be an octal so I replaced it for `mode=0O666` in all files with `mode` kwargs.

Hope this helps someone
